### ISSUE TITLE
No Log Files for RTView 0.2.0

### ISSUE THREAD

**Issue by ChristianMcCracken** [input-output-hk/cardano-rt-view#115] opened 2020-12-06 17:48 UTC
After a node crash I search for log files to identify the cause of the crash. I was unable to locate the log files. Using RTView 0.2.0 with cardano-node 1.23.0

**Comment by denisshevchenko** [comment] 2020-12-07 09:04
I'm closing this issue because it's a duplicate of an existing one: https://github.com/input-output-hk/cardano-rt-view/issues/45

**Closed as completed by denisshevchenko** 2020-12-07 09:04 UTC
